### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by EvlonLin** [sadanandpai/javascript-code-challenges#22]
https://github.com/sadanandpai/javascript-code-challenges/blame/main/challenges/primitives.md#L845
Should be:
- `Symbol.keyFor` method retrieves the name of the symbol

https://github.com/sadanandpai/javascript-code-challenges/blame/main/challenges/functions.md#L325
Should be:

`console.log("Parameter 1: " + param1);`

**Comment by sadanandpai** [comment]
Typos have been fixed. Thanks
