### ISSUE TITLE
Small typing mistake in write a program to append and prepend, single or multiple values in to an array

### ISSUE THREAD

**Issue by ppm143** [sadanandpai/javascript-code-challenges#28]
https://github.com/sadanandpai/javascript-code-challenges/blob/main/challenges/collections-concepts.md#Q2

const arr = [1, 2, 3];
const otherArr = [4, 5, 6];
arr.push(...otherArr);          // [1, 2, 3, 4, 5, 6]
arr.unshift(...arr);            // [4, 5, 6, 1, 2, 3, 4, 5, 6]   

it should be arr.unshilf(...otherArr) because in comment output is  [4, 5, 6, 1, 2, 3, 4, 5, 6]

**Comment by sadanandpai** [comment]
Fixed. Thanks
