### ISSUE TITLE
Collaboration with codedamn

### ISSUE THREAD

**Issue by mehulmpt** [sadanandpai/javascript-code-challenges#29]
Hi Sadanand
I came from your LinkedIn post on 2K stars. Congrats on that! I see a lot of challenges here are really good and cover a lot of important basics in JavaScript.

I'm the founder of codedamn (https://codedamn.com/) - an interactive learn-to-code platform where we focus a lot on full-stack web development and building practical, real-world skills for people (not just interview/DSA preparation)

Last month we launched a free interview-focused course on codedamn but with the focus on web development questions instead of standard DSA/competitive problems (https://codedamn.com/learn/web-development-interview). 

Seeing your repo, I feel like students can get a lot of benefits if we convert these questions into free hands-on practice labs on codedamn where they can practice their concepts and check if they did it right.

The repository is MIT licensed, but still, I'd love to see if you're up for this and potentially also include you in the process (giving up appropriate credits on the course page). If you'd like to take the conversation on email, I'm at mehul[at]codedamn[dot]com

Looking forward to hear from you.

**Comment by sadanandpai** [comment]
Thanks for reaching out. Happy to discuss about it
