### ISSUE TITLE
Update: Hacktoberfest

### ISSUE THREAD

**Issue by sadanandpai** [sadanandpai/javascript-code-challenges#56]
JavaScript Code Challenges is open for contributions for [Hacktoberfest](https://hacktoberfest.com/)

![hacktoberfest](https://github.com/sadanandpai/frontend-mini-challenges/assets/12962887/7a71bccb-90b9-4e6b-bbe2-24b475431aff)

All kinds of PRs are welcome but only the below ones are eligible for Hacktoberfest.

- Only new challenges are considered
- Before working on a PR for a new challenge, create an issue with the problem title to be added and assign it to yourself
- PR should be created to add a new challenge with a complete solution & details along
- PR should follow the [contribution guidelines](https://github.com/sadanandpai/javascript-code-challenges/blob/main/contributing.md)
- One PR per new challenge addition is considered
- Modification, updates, and documentation PR will not be eligible for Hacktoberfest

**Comment by Aditya-Singh2955** [comment]
Hi @sadanandpai please assign to me

**Comment by sadanandpai** [comment]
hi @Aditya-Singh2955 you can create a new issue and start working
